import React from 'react';

export const metadata = {
  title: 'Privacy Policy | Band Shakthi',
  description: 'Privacy policy and data protection guidelines for Band Shakthi online ticket buyers.',
};

export default function PrivacyPage() {
  return (
    <div style={{
      background: '#070709',
      color: '#ffffff',
      minHeight: '100vh',
      fontFamily: "'Outfit', 'Inter', sans-serif",
      padding: '60px 20px'
    }}>
      <div style={{
        maxWidth: '800px',
        margin: '0 auto',
        background: 'rgba(255, 255, 255, 0.02)',
        border: '1px solid rgba(228, 166, 47, 0.15)',
        borderRadius: '16px',
        padding: '40px',
        backdropFilter: 'blur(10px)',
        boxShadow: '0 10px 40px rgba(0,0,0,0.5)'
      }}>
        {/* Back Link */}
        <a href="/" style={{
          color: '#e4a62f',
          textDecoration: 'none',
          fontSize: '0.9rem',
          display: 'inline-flex',
          alignItems: 'center',
          gap: '6px',
          marginBottom: '30px',
          fontWeight: '600',
          textTransform: 'uppercase',
          letterSpacing: '0.05em'
        }}>
          ← Back To Home
        </a>

        {/* Title */}
        <h1 style={{
          fontFamily: "'Montserrat', sans-serif",
          fontSize: '2.2rem',
          fontWeight: '800',
          color: '#e4a62f',
          textTransform: 'uppercase',
          letterSpacing: '0.05em',
          marginBottom: '8px',
          borderBottom: '2px solid rgba(228, 166, 47, 0.2)',
          paddingBottom: '16px'
        }}>
          Privacy Policy
        </h1>
        <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.85rem', marginBottom: '32px' }}>
          Last Updated: July 15, 2026
        </p>

        {/* Content */}
        <div style={{
          lineHeight: '1.7',
          fontSize: '1rem',
          color: 'rgba(255, 255, 255, 0.85)',
          display: 'flex',
          flexDirection: 'column',
          gap: '24px'
        }}>
          <section>
            <h2 style={{ color: '#e4a62f', fontSize: '1.25rem', fontWeight: '700', marginBottom: '10px', textTransform: 'uppercase' }}>
              1. Information We Collect
            </h2>
            <p>
              When you purchase a ticket online or inquire through our forms, we collect the necessary personal identification details to fulfill your booking:
            </p>
            <ul style={{ paddingLeft: '20px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li><strong>Personal Details:</strong> Full Name, Email Address, and Mobile Phone Number.</li>
              <li><strong>Transaction Records:</strong> Billing and payment metadata generated by our authorized payment gateway service (we do not store credit card numbers or banking PINs on our servers).</li>
            </ul>
          </section>

          <section>
            <h2 style={{ color: '#e4a62f', fontSize: '1.25rem', fontWeight: '700', marginBottom: '10px', textTransform: 'uppercase' }}>
              2. How We Use Your Information
            </h2>
            <p>
              Your data is collected and processed strictly to secure your event access and ensure dynamic entry verification:
            </p>
            <ul style={{ paddingLeft: '20px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li>To compile entry passes, dispatch secure email tickets, and pre-fill direct WhatsApp receipt templates.</li>
              <li>To perform secure gate check-ins when our scanner reads your ticket QR code.</li>
              <li>To contact you with urgent updates regarding event timing shifts, postponements, or cancellations.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ color: '#e4a62f', fontSize: '1.25rem', fontWeight: '700', marginBottom: '10px', textTransform: 'uppercase' }}>
              3. Data Security & Storage
            </h2>
            <p>
              We prioritize customer data security. Your ticket details, buyer logs, and entry check-ins are stored inside highly secure, encrypted cloud databases. Only authorized personnel have secure access to view or manage guest lists.
            </p>
          </section>

          <section>
            <h2 style={{ color: '#e4a62f', fontSize: '1.25rem', fontWeight: '700', marginBottom: '10px', textTransform: 'uppercase' }}>
              4. Third-Party Sharing
            </h2>
            <p>
              We do **not** sell, rent, or trade your personal information to third-party advertisers. Your information is only shared with trusted processors required to complete operations:
            </p>
            <ul style={{ paddingLeft: '20px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li><strong>Payment Gateway:</strong> Our licensed third-party payment processor to safely process payments and execute secure transactions.</li>
              <li><strong>Secure Database Service:</strong> Our encrypted cloud database infrastructure to safely store, verify, and check-in tickets.</li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
}
